### ISSUE TITLE
Stream is very laggy

### ISSUE THREAD

**Issue by schichtenmacher** [jneilliii/OctoPrint-YouTubeLive#17]
settup works well, but how can i change fps for the youtube stream?
in octoprint the video is good with 30fps, but on youtube stream its very laggy

**Comment by jneilliii** [comment]
Because this is running on a pi and I didn't want to interfere with processing power I set the framerate pretty low (5 fps), so any changes may impact printing performance. That being said; if you modify the entry.sh file downloaded as part of the git pull in the instructions prior to building the docker image you can adjust any of the ffmpeg settings you want.  There's also an option to completely replace the command and stream h264 directly to YouTube with a raspicam (possibly others), see https://github.com/jneilliii/OctoPrint-YouTubeLive/issues/9#issuecomment-370252627 for more details.  The caveat to the later option is you have to also disable the built-in mjpeg stream.
